"""add updated_at to ReadingProgress

Revision ID: 016ab402ba3a
Revises: c08ac2927dcc
Create Date: 2026-05-30 16:54:59.619528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016ab402ba3a'
down_revision = 'c08ac2927dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
