"""Add club message model

Revision ID: 1bc3c2b3b3ad
Revises: 74c4e23bfaed
Create Date: 2026-05-29 14:54:30.558285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc3c2b3b3ad'
down_revision = '74c4e23bfaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['book_club.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('club_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_club_message_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_club_message_timestamp'))

    op.drop_table('club_message')
    # ### end Alembic commands ###
