"""Add avatar to user

Revision ID: 74c4e23bfaed
Revises: a21e9ff5c97b
Create Date: 2026-05-29 13:17:11.341345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c4e23bfaed'
down_revision = 'a21e9ff5c97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_file', sa.String(length=20), server_default='default.jpg', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_file')

    # ### end Alembic commands ###
