"""Add series info

Revision ID: 77a488f11cc2
Revises: 66da917ee893
Create Date: 2026-05-27 16:11:28.912150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a488f11cc2'
down_revision = '66da917ee893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_club', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_club_name'), ['name'], unique=True)

    op.create_table('club_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['book_club.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'club_id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_name', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('volume_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('volume_number')
        batch_op.drop_column('series_name')

    op.drop_table('club_members')
    with op.batch_alter_table('book_club', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_club_name'))

    op.drop_table('book_club')
    # ### end Alembic commands ###
