"""Add about_me and book summary

Revision ID: 8fa06599b180
Revises: 28127d985aa8
Create Date: 2026-05-29 15:48:25.159575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa06599b180'
down_revision = '28127d985aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about_me')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
